apiVersion: v1
kind: Service
metadata:
  name: hello-go
  namespace: istio-public
  labels:
    app: hello-go
spec:
  type: ClusterIP
  ports:
  - port: 9090
    name: http
  selector:
    app: hello-go
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-go
  namespace: istio-public
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: hello-go
        version: v1
    spec:
      containers:
      - name: hello-go
        image: {{.image}}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9090
