apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: hello-go-virtual-service
  namespace: istio-public
spec:
  hosts:
  - hello-go.com
  - www.hello-go.com
  gateways:
  - mesh
  - gateway-example.istio-system.svc.cluster.local
  http:
  - route:
    - destination:
        host: hello-go
        port:
          number: 9090
